name: Release
on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  update-autorevision:
    name: "Update AutoRevision"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update AutoRevision
        # Make sure there are no unstaged changes
        # Was reporting changes to eol=crlf files in .gitattributes
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git checkout -- .
          git rev-parse --short=5 HEAD > cmake/AutoRevision.txt
          git describe --tags `git rev-list --tags --max-count=1` >> cmake/AutoRevision.txt
          cat cmake/AutoRevision.txt
      - name: Find target branch
        id: branch
        # We're running on a tag so have no direct access to the branch. Find it.
        # Strip the first 3 components (ref/remotes/username)
        run: |
          branch=$(git branch -r --contains HEAD --format '%(refname:strip=3)')
          echo Target branch is $branch
          echo branch=$branch >> $GITHUB_OUTPUT
      - name: Problem file cleanup
        # We have this problematic file that we need to remove
        run: |
          rm -f dist/windows/freeciv21-server.cmd
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ steps.branch.outputs.branch }}
          commit-message: "Release update of AutoRevision.txt"
          branch: release/autorevision/${{ steps.branch.outputs.branch }}
          # Ensure we only add the changed cmake/AutoRevision.txt file in the commit
          add-paths: |
            cmake/AutoRevision.txt
          title: "Release update of AutoRevision.txt"
          body: >
            Automatic changes triggered by a new release.

            This PR updates `${{ steps.branch.outputs.branch }}`.
            Close and reopen this pull request to start the CI.
          delete-branch: true

  update-archive:
    name: "Update Source Archive"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # Make sure there are no unstaged changes
        # Was reporting changes to eol=crlf files in .gitattributes
      - name: Update AutoRevision
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git checkout -- .
          git rev-parse --short=5 HEAD > cmake/AutoRevision.txt
          git describe --tags `git rev-list --tags --max-count=1` >> cmake/AutoRevision.txt
          cat cmake/AutoRevision.txt
      - name: Make build directory
        run: mkdir -p -v $PWD/build
      - name: Create tar.gz
        run: |
          tar --exclude='build' --exclude='data/graphics' -cvzf Freeciv21-${{github.ref_name}}.tar.gz ../freeciv21/*
          sha256sum --binary Freeciv21-${{github.ref_name}}.tar.gz > Freeciv21-${{github.ref_name}}.tar.gz.sha256
      - name: Create zip
        run: |
          cd ..
          zip -r freeciv21/Freeciv21-${{github.ref_name}}.zip freeciv21/* -x \*/build/* \*.gz \*.sha256 \*/data/graphics/* \*/.*
          cd freeciv21
          sha256sum --binary Freeciv21-${{github.ref_name}}.zip > Freeciv21-${{github.ref_name}}.zip.sha256
      - name: Upload package
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Freeciv21-${{github.ref_name}}.tar.gz
            Freeciv21-${{github.ref_name}}.tar.gz.sha256
            Freeciv21-${{github.ref_name}}.zip
            Freeciv21-${{github.ref_name}}.zip.sha256

  snapcraft:
    name: "Snap Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup mirror
        run: |
          sudo sed -i 's/archive\.ubuntu\.com/azure.archive.ubuntu.com/g' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
      - name: Install base dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            git \
            cmake \
            ninja-build \
            python3 \
            gettext \
            gstreamer1.0-plugins-base \
            liblua5.3-dev \
            libsqlite3-dev \
            libsdl2-mixer-dev \
            libzstd-dev \
            liblzma-dev \
            libbz2-dev \
            snapd
      # snaps can't be built inside of a docker container, so we have to manually install our required dependencies
      - name: QT 6.8 LTS
        run: |
          # Qt Base
          wget https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtbase-everywhere-src-6.8.3.tar.xz
          tar xf qtbase-everywhere-src-6.8.3.tar.xz
          rm qtbase-everywhere-src-6.8.3.tar.xz
          cd qtbase-everywhere-src-6.8.3
          ./configure
          cmake --build . --parallel
          sudo cmake --install .
          cd ..
          rm -Rf qtbase-everywhere-src-6.8.3

          # Qt Multimedia
          wget https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtshadertools-everywhere-src-6.8.3.tar.xz
          tar xf qtshadertools-everywhere-src-6.8.3.tar.xz
          rm qtshadertools-everywhere-src-6.8.3.tar.xz
          cd qtshadertools-everywhere-src-6.8.3
          /usr/local/Qt-6.8.3/bin/qt-configure-module .
          cmake --build . --parallel
          sudo cmake --install .
          cd ..
          rm -Rf qtshadertools-everywhere-src-6.8.3

          wget https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtmultimedia-everywhere-src-6.8.3.tar.xz
          tar xf qtmultimedia-everywhere-src-6.8.3.tar.xz
          rm qtmultimedia-everywhere-src-6.8.3.tar.xz
          cd qtmultimedia-everywhere-src-6.8.3
          /usr/local/Qt-6.8.3/bin/qt-configure-module .
          cmake --build . --parallel
          sudo cmake --install .
          cd ..
          rm -Rf qtmultimedia-everywhere-src-6.8.3

          # Qt SVG
          wget https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtsvg-everywhere-src-6.8.3.tar.xz
          tar xf qtsvg-everywhere-src-6.8.3.tar.xz
          rm qtsvg-everywhere-src-6.8.3.tar.xz
          cd qtsvg-everywhere-src-6.8.3
          /usr/local/Qt-6.8.3/bin/qt-configure-module .
          cmake --build . --parallel
          sudo cmake --install .
          cd ..
          rm -Rf qtsvg-everywhere-src-6.8.3
      - name: KDE ECM
        run: |
          wget -O ecm.tar.gz https://github.com/KDE/extra-cmake-modules/archive/refs/tags/v6.7.0.tar.gz
          tar xf ecm.tar.gz
          rm ecm.tar.gz
          cd extra-cmake-modules-6.7.0
          cmake . -B build -G Ninja
          cmake --build build
          sudo cmake --build build --target install
          cd ..
          rm -Rf extra-cmake-modules-6.7.0
      - name: KDE KfArchive
        run: |
          wget https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qttools-everywhere-src-6.8.3.tar.xz
          tar xf qttools-everywhere-src-6.8.3.tar.xz
          rm qttools-everywhere-src-6.8.3.tar.xz
          cd qttools-everywhere-src-6.8.3
          /usr/local/Qt-6.8.3/bin/qt-configure-module .
          cmake --build . --parallel
          sudo cmake --install .
          cd ..
          rm -Rf qttools-everywhere-src-6.8.3

          wget -O kfa.tar.gz https://github.com/KDE/karchive/archive/refs/tags/v6.7.0.tar.gz
          tar xf kfa.tar.gz
          cd karchive-6.7.0
          cmake . -B build -G Ninja -DCMAKE_PREFIX_PATH=/usr/local/Qt-6.8.3
          cmake --build build
          sudo cmake --build build --target install
          cd ..
          rm -Rf karchive-6.7.0
      - name: Configure
        run: |
          mkdir -vp build/snap/local
          cp data/icons/128x128/freeciv21-client.png build/snap/local
          cmake . -B build -G Ninja -DCMAKE_PREFIX_PATH=/usr/local/Qt-6.8.3
      - name: Build and Upload
        uses: snapcore/action-build@v1
         id: snapcraft
         with:
           path: build
      # uses: snapcore/action-publish@v1
      #   env:
      #     SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      #   with:
      #     snap: ${{ steps.snapcraft.outputs.snap }}
      #     release: edge
